# Generated by Django 3.2.3 on 2021-06-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hblog', '0003_auto_20210609_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
