# Generated by Django 3.2.3 on 2021-06-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hblog', '0005_auto_20210627_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click link to read post', max_length=255),
        ),
    ]
